# Generated by Django 4.1.5 on 2023-02-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_user_userapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userapp',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
